### ISSUE TITLE
.NET FX 4.6 TryAdd failure!

### ISSUE THREAD

**Issue by xlievo** [danielkylewood/concurrent-linked-list#2]
.NET FX 4.6  After TryAdd, State = INV
Standard 2.0 does not have this problem!

if (!argAttr.TryAdd(attr))
{
       System.Console.WriteLine("ConcurrentLinkedList TryAdd error! State = INV");
}

Should I give up using .NET FX 4.6?

**Comment by danielkylewood** [comment]
Hey - the project targets .Net Standard 2.0, which is not supported by .NET FX 4.6.

You could try upgrading to .NET FX 4.6.1, which does support .Net Standard 2.0. I've tested in 4.6.1 and seems to work okay.

See compatibility table here for reference: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by xlievo** [comment]
Thank you for your reply. I'll check him again.
